///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("1f5d9fe7-0166-4043-9df5-2692d611ebe3")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        MyTestRepositoryFolders.ExplorerAppFolder _explorer;
        MyTestRepositoryFolders.CortanaAppFolder _cortana;
        MyTestRepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("1f5d9fe7-0166-4043-9df5-2692d611ebe3")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "1f5d9fe7-0166-4043-9df5-2692d611ebe3", ".\\RepositoryImages\\MyTestRepository1f5d9fe7.rximgres")
        {
            _applicationundertest = new MyTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _explorer = new MyTestRepositoryFolders.ExplorerAppFolder(this);
            _cortana = new MyTestRepositoryFolders.CortanaAppFolder(this);
            _calculator = new MyTestRepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("1f5d9fe7-0166-4043-9df5-2692d611ebe3")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("93d79ae8-a2a3-4601-8b53-52881345ced0")]
        public virtual MyTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("c6933ce8-6ce7-4642-b2c7-3a8f7e419c09")]
        public virtual MyTestRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Cortana folder.
        /// </summary>
        [RepositoryFolder("56cb03c6-4943-4b59-887d-84fff19d58ae")]
        public virtual MyTestRepositoryFolders.CortanaAppFolder Cortana
        {
            get { return _cortana; }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("9f610727-e33f-496c-a5ba-87694fc55520")]
        public virtual MyTestRepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("93d79ae8-a2a3-4601-8b53-52881345ced0")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            MyTestRepositoryFolders.RxTabIntroductionFolder _rxtabintroduction;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/form[@processname='RxDemoApp']", parentFolder, 30000, null, true, "93d79ae8-a2a3-4601-8b53-52881345ced0", "")
            {
                _rxtabintroduction = new MyTestRepositoryFolders.RxTabIntroductionFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("93d79ae8-a2a3-4601-8b53-52881345ced0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("93d79ae8-a2a3-4601-8b53-52881345ced0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("3d07afe1-7164-4c32-9cfb-aa2167a57b95")]
            public virtual MyTestRepositoryFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("3d07afe1-7164-4c32-9cfb-aa2167a57b95")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _reset1Info;
            RepoItemInfo _lblwelcomemessageInfo;
            RepoItemInfo _txtusernameInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "3d07afe1-7164-4c32-9cfb-aa2167a57b95", "")
            {
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/text[@accessiblename='Enter your name']", 30000, null, "6227c069-7577-4eba-8acf-6fde8ffc57ca");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "button[@controlname='btnSubmitUserName']", 30000, null, "a71ed2c2-39a8-4df3-8a78-78d5015c61d5");
                _reset1Info = new RepoItemInfo(this, "Reset1", "link[@controlname='RxLinkBtnReset']/?/?/link[@accessiblename='Reset']", 30000, null, "bfe9c208-735c-4fba-a014-440ffbde8f8d");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "text[@controlname='lblWelcomeMessage']", 30000, null, "6c03c2fd-f90d-4cbb-b107-260de4cbeebf");
                _txtusernameInfo = new RepoItemInfo(this, "TxtUserName", "text[@controlname='txtUserName']", 30000, null, "01d962ec-81d4-40f3-9307-21ddcbd7b03f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3d07afe1-7164-4c32-9cfb-aa2167a57b95")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3d07afe1-7164-4c32-9cfb-aa2167a57b95")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("6227c069-7577-4eba-8acf-6fde8ffc57ca")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("6227c069-7577-4eba-8acf-6fde8ffc57ca")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("a71ed2c2-39a8-4df3-8a78-78d5015c61d5")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("a71ed2c2-39a8-4df3-8a78-78d5015c61d5")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The Reset1 item.
            /// </summary>
            [RepositoryItem("bfe9c208-735c-4fba-a014-440ffbde8f8d")]
            public virtual Ranorex.Link Reset1
            {
                get
                {
                    return _reset1Info.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The Reset1 item info.
            /// </summary>
            [RepositoryItemInfo("bfe9c208-735c-4fba-a014-440ffbde8f8d")]
            public virtual RepoItemInfo Reset1Info
            {
                get
                {
                    return _reset1Info;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("6c03c2fd-f90d-4cbb-b107-260de4cbeebf")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("6c03c2fd-f90d-4cbb-b107-260de4cbeebf")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }

            /// <summary>
            /// The TxtUserName item.
            /// </summary>
            [RepositoryItem("01d962ec-81d4-40f3-9307-21ddcbd7b03f")]
            public virtual Ranorex.Text TxtUserName
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtUserName item info.
            /// </summary>
            [RepositoryItemInfo("01d962ec-81d4-40f3-9307-21ddcbd7b03f")]
            public virtual RepoItemInfo TxtUserNameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("c6933ce8-6ce7-4642-b2c7-3a8f7e419c09")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text4101Info;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "c6933ce8-6ce7-4642-b2c7-3a8f7e419c09", "")
            {
                _text4101Info = new RepoItemInfo(this, "Text4101", "?/?/text[@controlid='4101']", 30000, null, "c685b377-eacc-4c17-9b37-2365d2163656");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c6933ce8-6ce7-4642-b2c7-3a8f7e419c09")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c6933ce8-6ce7-4642-b2c7-3a8f7e419c09")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text4101 item.
            /// </summary>
            [RepositoryItem("c685b377-eacc-4c17-9b37-2365d2163656")]
            public virtual Ranorex.Text Text4101
            {
                get
                {
                    return _text4101Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text4101 item info.
            /// </summary>
            [RepositoryItemInfo("c685b377-eacc-4c17-9b37-2365d2163656")]
            public virtual RepoItemInfo Text4101Info
            {
                get
                {
                    return _text4101Info;
                }
            }
        }

        /// <summary>
        /// The CortanaAppFolder folder.
        /// </summary>
        [RepositoryFolder("56cb03c6-4943-4b59-887d-84fff19d58ae")]
        public partial class CortanaAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _id107Info;

            /// <summary>
            /// Creates a new Cortana  folder.
            /// </summary>
            public CortanaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Cortana", "/winapp[@packagename='Microsoft.Windows.Cortana']", parentFolder, 30000, null, true, "56cb03c6-4943-4b59-887d-84fff19d58ae", "")
            {
                _id107Info = new RepoItemInfo(this, "Id107", ".//list[@automationid='suggestionsList']/listitem[@automationid='id_107']", 30000, null, "5199f020-61c8-4254-84d7-4f1d671e847f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("56cb03c6-4943-4b59-887d-84fff19d58ae")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("56cb03c6-4943-4b59-887d-84fff19d58ae")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Id107 item.
            /// </summary>
            [RepositoryItem("5199f020-61c8-4254-84d7-4f1d671e847f")]
            public virtual Ranorex.ListItem Id107
            {
                get
                {
                    return _id107Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Id107 item info.
            /// </summary>
            [RepositoryItemInfo("5199f020-61c8-4254-84d7-4f1d671e847f")]
            public virtual RepoItemInfo Id107Info
            {
                get
                {
                    return _id107Info;
                }
            }
        }

        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("9f610727-e33f-496c-a5ba-87694fc55520")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _num8buttonInfo;
            RepoItemInfo _multiplybuttonInfo;
            RepoItemInfo _equalbuttonInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "9f610727-e33f-496c-a5ba-87694fc55520", "")
            {
                _num8buttonInfo = new RepoItemInfo(this, "Num8Button", "?/?/container[@automationid='NumberPad']/button[@automationid='num8Button']", 30000, null, "a4c6784f-3763-4ab0-98ae-c4048f8f312c");
                _multiplybuttonInfo = new RepoItemInfo(this, "MultiplyButton", "?/?/container[@automationid='StandardOperators']/button[@automationid='multiplyButton']", 30000, null, "b9f60cb2-661f-407f-8b47-f4a932cc3968");
                _equalbuttonInfo = new RepoItemInfo(this, "EqualButton", "?/?/container[@automationid='StandardOperators']/button[@automationid='equalButton']", 30000, null, "f93275ff-fc4b-48d2-b78b-fd21567b411d");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@automationid='Close']", 30000, null, "ce0bdfcc-1d8b-44aa-aff7-0139fb107d37");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9f610727-e33f-496c-a5ba-87694fc55520")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9f610727-e33f-496c-a5ba-87694fc55520")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Num8Button item.
            /// </summary>
            [RepositoryItem("a4c6784f-3763-4ab0-98ae-c4048f8f312c")]
            public virtual Ranorex.Button Num8Button
            {
                get
                {
                    return _num8buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num8Button item info.
            /// </summary>
            [RepositoryItemInfo("a4c6784f-3763-4ab0-98ae-c4048f8f312c")]
            public virtual RepoItemInfo Num8ButtonInfo
            {
                get
                {
                    return _num8buttonInfo;
                }
            }

            /// <summary>
            /// The MultiplyButton item.
            /// </summary>
            [RepositoryItem("b9f60cb2-661f-407f-8b47-f4a932cc3968")]
            public virtual Ranorex.Button MultiplyButton
            {
                get
                {
                    return _multiplybuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MultiplyButton item info.
            /// </summary>
            [RepositoryItemInfo("b9f60cb2-661f-407f-8b47-f4a932cc3968")]
            public virtual RepoItemInfo MultiplyButtonInfo
            {
                get
                {
                    return _multiplybuttonInfo;
                }
            }

            /// <summary>
            /// The EqualButton item.
            /// </summary>
            [RepositoryItem("f93275ff-fc4b-48d2-b78b-fd21567b411d")]
            public virtual Ranorex.Button EqualButton
            {
                get
                {
                    return _equalbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EqualButton item info.
            /// </summary>
            [RepositoryItemInfo("f93275ff-fc4b-48d2-b78b-fd21567b411d")]
            public virtual RepoItemInfo EqualButtonInfo
            {
                get
                {
                    return _equalbuttonInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("ce0bdfcc-1d8b-44aa-aff7-0139fb107d37")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("ce0bdfcc-1d8b-44aa-aff7-0139fb107d37")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}